### ISSUE TITLE
Frage

### ISSUE THREAD

**Issue by FlxiBoy1313** [Shan15Dev/ShanBrowser-Chromium-#1]
Ist der Browser sicher?

**Comment by Shan15Dev** [comment]
Hallo!

Dieser Browser ist mein erstes richtiges grosses Projekt mit C# Winforms!
Daher kann es natürlich zu Problemen führen.

Der Browser ist mit der CefSharp Klasse aufgebaut und ich als Developer programmiere nur den Browser selbst mit den Einstellungen usw.

In der aktuellen Version gibt es NOCH keine Einstellungsmöglichkeiten. 
Da ich selbst die Sicherheit des Browsers nicht zu 100% garantieren kann würde ich empfehlen sich nirgends anzumelden auf den Browser.

Freundliche Grüsse!

**Comment by FlxiBoy1313** [comment]
Vielen dank.
Ich schätze ihre Sicherheit. Jedoch würde ein Speedtest der Telekom gehen?

**Comment by FlxiBoy1313** [comment]
sach mal
